[project]
name = "model-reasoning-power"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-ollama>=0.2.3",
    "langchain-openai>=0.3.6",
    "python-dotenv>=1.0.1",
]
